### ISSUE TITLE
World loading crash

### ISSUE THREAD

**Issue by DragonTamr34** [Hypeirochus/Starcraft-Mod#4]
Hello, I was exploring a world with this mod installed on version 1.12.2 and got this crash report (Don't know how to make it smaller sorry):

Description: Exception ticking world
java.lang.NullPointerException: Exception ticking world
	at com.hypeirochus.scmc.worldgen.structure.StructureTerranBarracksTemplate.generate(StructureTerranBarracksTemplate.java:1253)
	at com.hypeirochus.scmc.worldgen.structure.StructureTerranBarracksTemplate.generate(StructureTerranBarracksTemplate.java:26)
	at com.hypeirochus.scmc.handlers.StarcraftGenerator.runGenericFlagGenerator(StarcraftGenerator.java:200)
	at com.hypeirochus.scmc.worldgen.StarcraftWorldGenerationContainer.generateOverworld(StarcraftWorldGenerationContainer.java:90)
	at com.hypeirochus.scmc.handlers.WorldGenerationHandler.generate(WorldGenerationHandler.java:34)
If you need more of it let me know.

**Comment by DragonTamr34** [comment]
It seems to happen whenever a structure is loaded, no matter what kind because a command center loaded and I crashed. I know this version is incomplete and the mod itself is also so I do not know if you are aware of this issue or if it is a generator conflict.

**Comment by ghost** [comment]
This is a known issue that we are working on fixing in the upcoming release. Thanks for raising more awareness for it though. 😄 Also for future reference, please put crash reports in a [https://pastebin.com/](url).

**Comment by Ocelot5836** [comment]
I'll look into finishing the *boring* structures

**Comment by cyb3rm4n** [comment]
Got the new error:

java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
	at com.arpaesis.scmc.quests.Quest.<init>(Quest.java:27)
	at com.arpaesis.scmc.quests.Quests.register(Quests.java:48)
	at com.arpaesis.scmc.quests.Quests.<clinit>(Quests.java:31)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_5_Quests_onAdvancementComplete_AdvancementEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onAdvancement(ForgeHooks.java:1401)
	at net.minecraft.advancements.PlayerAdvancements.func_192750_a(PlayerAdvancements.java:221)
	at net.minecraft.advancements.ICriterionTrigger$Listener.func_192159_a(SourceFile:31)
	at net.minecraft.advancements.critereon.TickTrigger$Listeners.func_193503_b(SourceFile:92)
	at net.minecraft.advancements.critereon.TickTrigger.func_193182_a(SourceFile:60)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:368)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:642)
	at net.minecraft.world.World.func_72939_s(World.java:1734)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: scala.actors.threadpool.Arrays
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 23 more
Caused by: java.lang.NullPointerException
